# Generated by Django 3.2 on 2023-04-20 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titles',
            name='categories',
            field=models.ForeignKey(blank=True, help_text='Категория произведения', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='titles', to='titles.categories', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='titles',
            name='genre',
            field=models.ForeignKey(blank=True, help_text='Жанр произведения', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='titles', to='titles.genres', verbose_name='Жанр'),
        ),
    ]
